# Generated by Django 2.1.5 on 2019-02-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_reflinks', '0002_referralhit_http_referer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralhit',
            name='next',
            field=models.URLField(blank=True, help_text='The ?next parameter when the link was hit.', max_length=500),
        ),
    ]
